FROM node:lts-alpine AS builder
ARG NEXT_PUBLIC_APIDOC_URL
ENV NEXT_PUBLIC_APIDOC_URL ${NEXT_PUBLIC_APIDOC_URL}
WORKDIR /builder
COPY . .
RUN npm ci
RUN npx openapi2aspida -i ${NEXT_PUBLIC_APIDOC_URL}
RUN NODE_ENV=production npm run build

FROM node:lts-alpine AS production
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG NEXT_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_FIREBASE_API_KEY ${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
ENV NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID ${NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID}
ENV NEXT_PUBLIC_FIREBASE_APP_ID ${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
ENV NEXT_PUBLIC_SERVER_URL ${NEXT_PUBLIC_SERVER_URL}
ENV NODE_ENV=production
WORKDIR /app
COPY --from=builder /builder/package.json /builder/package-lock.json ./
COPY --from=builder /builder/api ./api
COPY --from=builder /builder/.next ./.next
COPY --from=builder /builder/public ./public
RUN npm i next aspida

EXPOSE $PORT
ENTRYPOINT ["npm", "run", "start"]
