version: '3'

services:
  app:
    build: .
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/workspace:cached
      - node-modules:/workspace/node_modules

volumes:
  node-modules:
