name: Deploy

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  PORT: ${{ secrets.PORT }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
  NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
  NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
  NEXT_PUBLIC_APIDOC_URL: ${{ secrets.NEXT_PUBLIC_APIDOC_URL }}

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: >
          docker build -t $IMAGE . --build-arg
          "NEXT_PUBLIC_APIDOC_URL"="${{ secrets.NEXT_PUBLIC_APIDOC_URL }}"
          "NEXT_PUBLIC_FIREBASE_API_KEY"="${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}"
          "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"="${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}"
          "NEXT_PUBLIC_FIREBASE_PROJECT_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}"
          "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"="${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}"
          "NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID }}"
          "NEXT_PUBLIC_FIREBASE_APP_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}"
          "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}"

      - name: Push the docker image to Container Registry
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --port $PORT \
            --project $GCP_PROJECT_ID \
            --region $GCP_REGION \
            --platform=managed \
            --allow-unauthenticated \
            --quiet \
            --set-env-vars="NEXT_PUBLIC_FIREBASE_API_KEY"="${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" \
            --set-env-vars="NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"="${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" \
            --set-env-vars="NEXT_PUBLIC_FIREBASE_PROJECT_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" \
            --set-env-vars="NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"="${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" \
            --set-env-vars="NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID }}" \
            --set-env-vars="NEXT_PUBLIC_FIREBASE_APP_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" \
            --set-env-vars="NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"="${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" \
            --set-env-vars="NEXT_PUBLIC_SERVER_URL"="${{ secrets.NEXT_PUBLIC_SERVER_URL }}" \
            --set-env-vars="NEXT_PUBLIC_APIDOC_URL"="${{ secrets.NEXT_PUBLIC_APIDOC_URL }}"
